// servicesData.js

export const ServicesMenu = {
  label: "Services",
  options: [
    {
      label: "Organic Villa",
      link: "/servicePage/organic-villa",
      image: "/assets/Organic-villa.png",
      type: "service",
      desc: "Providing eco-friendly and sustainable organic living solutions for healthier lifestyles.",
      process: [
        { title: "Initial Consultation", desc: "We understand client needs and lifestyle goals." },
        { title: "Site Analysis", desc: "Eco-friendly material selection based on site evaluation." },
        { title: "Implementation", desc: "Deploy sustainable solutions tailored to client needs." },
        { title: "Post-Installation Support", desc: "Provide ongoing support and guidance for maintenance." },
      ],
      highlights: [
        { icon: "bi-leaf", title: "Eco-Friendly", desc: "Built with sustainable materials" },
        { icon: "bi-house", title: "Healthy Living", desc: "Promotes organic lifestyles" },
        { icon: "bi-people", title: "Community Impact", desc: "Supports a greener future" },
      ],
    },
    {
      label: "Gardening",
      link: "/servicePage/gardening",
      image: "/assets/Gardening.png",
      type: "service",
      desc: "Complete gardening solutions including setup, maintenance, and seasonal care.",
      process: [
        { title: "Soil Testing", desc: "Analyze and prepare soil for healthy plant growth." },
        { title: "Plant Selection", desc: "Choose plants suited to climate and conditions." },
        { title: "Setup", desc: "Planting and irrigation system installation." },
        { title: "Maintenance", desc: "Ongoing care, monitoring, and seasonal upkeep." },
      ],
      highlights: [
        { icon: "bi-flower1", title: "Beautiful Gardens", desc: "Custom designs for your space" },
        { icon: "bi-droplet", title: "Irrigation", desc: "Smart water management" },
        { icon: "bi-heart", title: "Sustainability", desc: "Eco-friendly gardening methods" },
      ],
    },
    {
      label: "Landscaping",
      link: "/servicePage/landscaping",
      image: "/assets/Landscaping.png",
      type: "service",
      desc: "Professional landscaping services to enhance the aesthetics and functionality of spaces.",
      process: [
        { title: "Consultation & Planning", desc: "Discuss design ideas and client preferences." },
        { title: "3D Visualization", desc: "Provide layouts and virtual previews." },
        { title: "Ground Preparation", desc: "Level and prepare the land for landscaping." },
        { title: "Implementation", desc: "Execute design with plants, decor, and structures." },
      ],
      highlights: [
        { icon: "bi-brush", title: "Creative Designs", desc: "Custom layouts and visuals" },
        { icon: "bi-tree", title: "Natural Beauty", desc: "Enhances environment appeal" },
        { icon: "bi-geo", title: "Smart Planning", desc: "Functional outdoor spaces" },
      ],
    },
    {
      label: "Terrace Gardening",
      link: "/servicePage/terrace-gardening",
      image: "/assets/Terrace-gardening.png",
      type: "service",
      desc: "Convert unused rooftops into green, productive gardens.",
      process: [
        { title: "Waterproofing", desc: "Prepare terrace to avoid leakage and damage." },
        { title: "Soil & Containers", desc: "Set up lightweight soil mixes and planters." },
        { title: "Irrigation", desc: "Install efficient watering systems." },
        { title: "Planting & Monitoring", desc: "Add plants and provide regular check-ups." },
      ],
      highlights: [
        { icon: "bi-building", title: "Utilize Space", desc: "Transform rooftops into gardens" },
        { icon: "bi-droplet", title: "Water Systems", desc: "Irrigation for healthy growth" },
        { icon: "bi-sun", title: "Sustainable", desc: "Green solutions for cities" },
      ],
    },
    {
      label: "Indoor Gardening",
      link: "/servicePage/indoor-gardening",
      image: "/assets/Indoor-gardening.png",
      type: "service",
      desc: "Bring greenery inside homes and offices with tailored indoor plant setups.",
      process: [
        { title: "Lighting & Space Check", desc: "Assess space and natural light availability." },
        { title: "Plant Selection", desc: "Pick air-purifying and aesthetic plants." },
        { title: "Setup & Decoration", desc: "Arrange pots and decor for visual appeal." },
        { title: "Maintenance", desc: "Provide care routines and plant support." },
      ],
      highlights: [
        { icon: "bi-house-door", title: "Stylish Decor", desc: "Adds beauty indoors" },
        { icon: "bi-wind", title: "Air Quality", desc: "Purifies indoor air" },
        { icon: "bi-emoji-smile", title: "Well-being", desc: "Boosts mental health" },
      ],
    },
    {
      label: "Hydroponics",
      link: "/servicePage/hydroponics",
      image: "/assets/Hydroponics.png",
      type: "service",
      desc: "Soil-less farming solutions using nutrient-rich water systems.",
      process: [
        { title: "System Design", desc: "Choose NFT, DWC, or vertical hydroponic models." },
        { title: "Setup", desc: "Install trays, reservoirs, and nutrient supply." },
        { title: "Planting", desc: "Grow plants with water-based nutrient systems." },
        { title: "Training", desc: "Provide guidance for ongoing maintenance." },
      ],
      highlights: [
        { icon: "bi-beaker", title: "Soil-Free", desc: "Efficient water farming" },
        { icon: "bi-lightning", title: "High Yield", desc: "Faster plant growth" },
        { icon: "bi-droplet", title: "Nutrient Control", desc: "Balanced plant nutrition" },
      ],
    },
    {
      label: "Herbal Gardening",
      link: "/servicePage/herbal-gardening",
      image: "/assets/Herbal-Gardening.png",
      type: "service",
      desc: "Grow medicinal and aromatic herbs for health and wellness.",
      process: [
        { title: "Herb Selection", desc: "Pick medicinal and aromatic herbs." },
        { title: "Soil Preparation", desc: "Set up soil beds or pots for herbs." },
        { title: "Guidance", desc: "Educate on uses and benefits of herbs." },
        { title: "Harvesting", desc: "Provide maintenance and harvesting support." },
      ],
      highlights: [
        { icon: "bi-capsule", title: "Medicinal", desc: "Grow natural remedies" },
        { icon: "bi-flower1", title: "Aromatic", desc: "Fragrant herbs at home" },
        { icon: "bi-heart", title: "Wellness", desc: "Supports healthy living" },
      ],
    },
    {
      label: "Vertical Gardening",
      link: "/servicePage/vertical-gardening",
      image: "/assets/Vertical-gardening.png",
      type: "service",
      desc: "Space-saving gardening solutions using vertical walls.",
      process: [
        { title: "Wall Check", desc: "Assess wall surface and waterproofing." },
        { title: "Panel Installation", desc: "Install modular vertical garden panels." },
        { title: "Irrigation Setup", desc: "Implement drip irrigation system." },
        { title: "Planting", desc: "Arrange plants for aesthetic appeal." },
      ],
      highlights: [
        { icon: "bi-layers", title: "Space Saver", desc: "Ideal for small areas" },
        { icon: "bi-bricks", title: "Stylish Walls", desc: "Green vertical decor" },
        { icon: "bi-droplet", title: "Drip System", desc: "Efficient irrigation" },
      ],
    },
    {
      label: "Lab Testing",
      link: "/servicePage/lab-testing",
      image: "/assets/Lab.png",
      type: "service",
      desc: "Soil and water testing services to ensure healthy plant growth.",
      process: [
        { title: "Sample Collection", desc: "Gather soil and water samples from site." },
        { title: "Lab Analysis", desc: "Conduct nutrient and chemical tests." },
        { title: "Detailed Report", desc: "Provide comprehensive test results." },
        { title: "Recommendations", desc: "Suggest improvements for soil & water health." },
      ],
      highlights: [
        { icon: "bi-clipboard-data", title: "Accurate Testing", desc: "Reliable lab results" },
        { icon: "bi-bar-chart", title: "Detailed Reports", desc: "Nutrient breakdowns" },
        { icon: "bi-lightbulb", title: "Expert Advice", desc: "Actionable improvements" },
      ],
    },
    {
      label: "Quality Checking",
      link: "/servicePage/quality-checking",
      image: "/assets/Quality.png",
      type: "service",
      desc: "Inspection and quality assurance of gardening and farming setups.",
      process: [
        { title: "Inspection", desc: "Check soil, plant health, and conditions." },
        { title: "System Check", desc: "Inspect irrigation and drainage." },
        { title: "Pest & Disease Control", desc: "Monitor and prevent issues." },
        { title: "Final Report", desc: "Deliver a detailed quality assurance report." },
      ],
      highlights: [
        { icon: "bi-check2-circle", title: "Assurance", desc: "Reliable quality checks" },
        { icon: "bi-shield", title: "Protection", desc: "Pest and disease control" },
        { icon: "bi-bar-chart", title: "Performance", desc: "Ensure healthy growth" },
      ],
    },
    {
      label: "Trimming & Pruning",
      link: "/servicePage/trimming-pruning",
      image: "/assets/Trimming.png",
      type: "service",
      desc: "Professional trimming and pruning services for healthier plant growth.",
      process: [
        { title: "Assessment", desc: "Identify overgrown and weak plant parts." },
        { title: "Pruning", desc: "Use proper horticulture techniques and tools." },
        { title: "Waste Disposal", desc: "Dispose or compost waste responsibly." },
        { title: "Future Guidance", desc: "Provide plant care tips post-service." },
      ],
      highlights: [
        { icon: "bi-scissors", title: "Professional", desc: "Neat and healthy trimming" },
        { icon: "bi-tree", title: "Healthy Plants", desc: "Encourages fresh growth" },
        { icon: "bi-recycle", title: "Eco-Friendly", desc: "Composting waste" },
      ],
    },
    {
      label: "Consultation Services",
      link: "/servicePage/consultation",
      image: "/assets/Consultation.png",
      type: "service",
      desc: "Expert consultation on gardening, farming, and organic solutions.",
      process: [
        { title: "Requirement Analysis", desc: "Understand client’s gardening or farming needs." },
        { title: "Assessment", desc: "Conduct on-site or virtual evaluation." },
        { title: "Recommendations", desc: "Provide customized and practical solutions." },
        { title: "Support", desc: "Follow up with guidance and implementation help." },
      ],
      highlights: [
        { icon: "bi-person-workspace", title: "Expertise", desc: "Get guidance from experts" },
        { icon: "bi-lightbulb", title: "Innovative", desc: "Tailored creative solutions" },
        { icon: "bi-chat", title: "Support", desc: "Ongoing client support" },
      ],
    },
  ],
};

export default ServicesMenu;
