// servicesData.js

export const ServicesMenu = {
  label: "Services",
  options: [
    {
      label: "Organic Villa",
      link: "/ServicePage/organic-villa",
      image: "/assets/Organic-villa.png",
      type: "service",
      desc: "Providing eco-friendly and sustainable organic living solutions for healthier lifestyles.",
      process: [
        "Initial consultation to understand client needs",
        "Site analysis and eco-friendly material selection",
        "Implementation of organic lifestyle solutions",
        "Post-installation support and guidance",
      ],
    },
    {
      label: "Gardening",
      link: "/ServicePage/gardening",
      image: "/assets/Gardening.png",
      type: "service",
      desc: "Complete gardening solutions including setup, maintenance, and seasonal care.",
      process: [
        "Soil testing and preparation",
        "Plant selection based on climate",
        "Planting and irrigation setup",
        "Ongoing care and maintenance",
      ],
    },
    {
      label: "Landscaping",
      link: "/ServicePage/landscaping",
      image: "/assets/Landscaping.png",
      type: "service",
      desc: "Professional landscaping services to enhance the aesthetics and functionality of spaces.",
      process: [
        "Client consultation and design planning",
        "3D layout visualization",
        "Ground leveling and preparation",
        "Implementation of design with plants and decor",
      ],
    },
    {
      label: "Terrace Gardening",
      link: "/ServicePage/terrace-gardening",
      image: "/assets/Terrace-gardening.png",
      type: "service",
      desc: "Convert unused rooftops into green, productive gardens.",
      process: [
        "Waterproofing terrace surface",
        "Lightweight soil and container setup",
        "Installation of irrigation system",
        "Planting and ongoing monitoring",
      ],
    },
    {
      label: "Indoor Gardening",
      link: "/ServicePage/indoor-gardening",
      image: "/assets/Indoor-gardening.png",
      type: "service",
      desc: "Bring greenery inside homes and offices with tailored indoor plant setups.",
      process: [
        "Assessment of indoor lighting and space",
        "Selection of air-purifying and aesthetic plants",
        "Potting and decor arrangements",
        "Regular maintenance and plant care",
      ],
    },
    {
      label: "Hydroponics",
      link: "/ServicePage/hydroponics",
      image: "/assets/Hydroponics.png",
      type: "service",
      desc: "Soil-less farming solutions using nutrient-rich water systems.",
      process: [
        "Hydroponic system design (NFT, DWC, or vertical)",
        "Setup of grow trays and nutrient supply",
        "Planting and growth monitoring",
        "Training for long-term maintenance",
      ],
    },
    {
      label: "Herbal Gardening",
      link: "/ServicePage/herbal-gardening",
      image: "/assets/Herbal-Gardening.png",
      type: "service",
      desc: "Grow medicinal and aromatic herbs for health and wellness.",
      process: [
        "Selection of suitable herbal plants",
        "Preparation of soil beds or pots",
        "Guidance on usage and benefits",
        "Maintenance and harvesting support",
      ],
    },
    {
      label: "Vertical Gardening",
      link: "/ServicePage/vertical-gardening",
      image: "/assets/Vertical-gardening.png",
      type: "service",
      desc: "Space-saving gardening solutions using vertical walls.",
      process: [
        "Wall assessment and waterproofing",
        "Installation of vertical panels",
        "Drip irrigation system setup",
        "Plant selection and arrangement",
      ],
    },
    {
      label: "Lab Testing",
      link: "/ServicePage/lab-testing",
      image: "/assets/Lab.png",
      type: "service",
      desc: "Soil and water testing services to ensure healthy plant growth.",
      process: [
        "Sample collection from site",
        "Laboratory analysis of soil and water",
        "Detailed report with nutrient levels",
        "Recommendations for improvement",
      ],
    },
    {
      label: "Quality Checking",
      link: "/ServicePage/quality-checking",
      image: "/assets/Quality.png",
      type: "service",
      desc: "Inspection and quality assurance of gardening and farming setups.",
      process: [
        "Inspection of soil and plant health",
        "Check irrigation and drainage systems",
        "Pest and disease monitoring",
        "Final quality assurance report",
      ],
    },
    {
      label: "Trimming & Pruning",
      link: "/ServicePage/trimming-pruning",
      image: "/assets/Trimming.png",
      type: "service",
      desc: "Professional trimming and pruning services for healthier plant growth.",
      process: [
        "Assessment of overgrown plants",
        "Pruning using proper horticulture tools",
        "Waste disposal and composting",
        "Guidance on future plant care",
      ],
    },
    {
      label: "Consultation Services",
      link: "/ServicePage/consultation",
      image: "/assets/Consultation.png",
      type: "service",
      desc: "Expert consultation on gardening, farming, and organic solutions.",
      process: [
        "Understanding client requirements",
        "On-site or virtual assessment",
        "Customized solution recommendations",
        "Follow-up and implementation support",
      ],
    },
  ],
};

export default ServicesMenu;
